### PR TITLE
Added timezone field

### PR DESCRIPTION
**Pull request by PurpleBooth**
Added timezone field to help match availability

### CODE REVIEW

**Comment by PurpleBooth** [comment]
~~Unable to test this properly because of #61.~~

~~So review with care :smile:~~

@Xethron reviewed this and fixed a tiny bug with this, so we should be good!

**Comment by Xethron** [comment]
LGTM. And I think it would be a great help to get someone in a similar timezone as yourself.

**Comment by dragonmantank** [comment]
This looks like a good start to me, since the other PR we had for the timezones/geolocation was closed.

One definite thing I'd like to see is a validator to make sure the timezone entered is actually a valid one. I'd say just change it to a drop-down, but that would be a huge list. 

From there we can figure out the searching side, which needs to be more robust anyway. Storing the timezone will get us part of the way though.

**Comment by PurpleBooth** [comment]
That should have validation now.

**Pull request merged**
